[project]
name = "times-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "mcp>=1.14.1",
    "numpy>=2.3.3",
    "pathlib>=1.0.1",
    "pydantic>=2.11.9",
    "typing>=3.10.0.0",
]
