[project]
name = "times-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.6",
    "mcp[cli]>=1.7.1",
    "mpld3>=0.5.11",
    "numpy>=2.2.6",
    "plotly>=6.3.0",
    "sympy>=1.14.0",
]
